# Generated by Django 5.2 on 2025-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_profile_surname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="age",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="surname",
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
