# Generated by Django 5.2.1 on 2025-05-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_remove_article_is_published_article_status_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="article",
            managers=[],
        ),
    ]
