# Generated by Django 5.2.1 on 2025-05-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_alter_article_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
