# Generated by Django 5.2.1 on 2025-05-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_tag_article_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="is_published",
        ),
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-created_at"], name="posts_artic_created_7ffe95_idx"
            ),
        ),
    ]
